# Name of the Workflow
# 'name:' here in the first line is required
name: First Workflow

# This is the event that triggers this workflow to run
# 'on:' is required
### workflow_dispatch means manual trigger
on: workflow_dispatch

# Now we're getting to defining the jobs
# 'jobs:' here is required
jobs:

  # The name of the first job that this workflow is running
  # This is a user defined key, this can be anything we're just choosing to name it 'first-job'
  first-job:

    # Defining the runner, AKA the environment that the job will execute the following steps
    # 'runs-on:' here is required
    # supported runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest

    # Starting to define the steps to be executed
    # 'steps:' is required, it takes a list
    steps:
        # name of the step
      - name: print greeting
        # 'run' here defines the command that should be ran on the command line
        run: echo "Hello World!"

      - name: print goodbye
        run: echo "Done - bye!"
    

    

    
